"""users table add email

Revision ID: 31f2638f88ba
Revises: f772092dd41f
Create Date: 2025-06-21 20:57:43.649754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f2638f88ba'
down_revision = 'f772092dd41f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_user_lastname'))
        batch_op.create_index(batch_op.f('ix_user_lastname'), ['lastname'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_lastname'))
        batch_op.create_index(batch_op.f('ix_user_lastname'), ['lastname'], unique=False)
        batch_op.alter_column('lastname',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###
