"""users table add email

Revision ID: 57cad94e5f00
Revises: 31f2638f88ba
Create Date: 2025-06-21 20:58:24.807819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57cad94e5f00'
down_revision = '31f2638f88ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=16),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_user_lastname'))
        batch_op.create_index(batch_op.f('ix_user_lastname'), ['lastname'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_lastname'))
        batch_op.create_index(batch_op.f('ix_user_lastname'), ['lastname'], unique=1)
        batch_op.alter_column('lastname',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
