"""users table add admin column

Revision ID: 95baec0e2af9
Revises: 57cad94e5f00
Create Date: 2025-06-22 06:31:20.766129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95baec0e2af9'
down_revision = '57cad94e5f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
